name: Terraform Infrastructure Deploy

on:
  push:

    branches:
    - main
env:
  AWS_REGION: us-west-2


jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:

    
    - name: Checkout Code
      uses: actions/checkout@v4

    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}


    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v4

    
    - name: Terraform Init
      run: terraform init


    - name: Terraform Plan
      run: terraform plan 

    - name: Terraform Apply
      run: terraform apply -auto-approve 
      env:
        TF_VAR_org_name: ${{ secrets.ORG_NAME }}
        TF_VAR_service_account_name: ${{ secrets.SA_NAME }}
        TF_VAR_project_name: ${{ secrets.PROJECT_NAME }}
        TF_VAR_cluster_name: ${{ secrets.CLUSTER_NAME }}
        TF_VAR_aws_region: ${{ env.AWS_REGION }}
        TF_VAR_db_username: ${{ secrets.DB_USERNAME }}
        TF_VAR_db_name: ${{ secrets.DB_NAME }}
        TF_VAR_atlas_secret_name: ${{ secrets.ATLAS_SECRET_NAME }}
